version: 0.2 
phases:
  install:
    runtime-versions:
      java : corretto17
  pre_build:
    commands:
      - echo "pre-build started"
      - pwd
      - ls -lrta
  build:
    commands:
      - echo Build started on `date`
      #- mvn clean validate compile test install verify package
      - cp -pvr settings.xml /root/.m2/settings.xml
      - ls -lrt /root/.m2/settings.xml
      # - mvn clean verify sonar:sonar
      #- export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain mom --domain-owner 225989338000 --region ap-south-1 --query authorizationToken --output text`
      # - mvn deploy -DskipTests=true 
      - mvn package -DskipTests=true
      # - curl -u admin:admin123 -T target/*.war "http://40.192.110.39:8080/manager/text/deploy?path=/eg&update=true"
      # - echo Build completed on `date`
  post_build:
    commands:
      # - echo Deliver Artifact To Remote Tomcat Server `date`
      # - echo "Deploying to Tomcat..."
      # - WAR_FILE=$(ls target/*.war | head -n 1)
      # - echo "Deploying $WAR_FILE"
      # - curl --fail --show-error --silent \
      #   -u admin:admin123 \
      #   -T $WAR_FILE \
      #   "http://40.192.110.39:8080/manager/text/deploy?path=/eg&update=true"
artifacts:
  base-directory: target
  files:
    - target/*.war
    - target/*.jar